### ISSUE TITLE
Ruby and JS have sets

### ISSUE THREAD

**Issue by hwayne** [oscar-barlow/java-quickstart#3]
> Java has data structures that neither Ruby nor Javascript have, like Sets. Addtionally, many of these classes are abstract and can't or shouldn't be instantiated directly.

* https://ruby-doc.org/stdlib-2.5.1/libdoc/set/rdoc/Set.html
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by oscar-barlow** [comment]
Many thanks. Fixed by https://github.com/oscar-barlow/java-quickstart/commit/dbaec0b21bf7f4ef2d69bc89b1489f44f06d6e2e
